services:
  # =============== FRONTEND (Angular 20) ===============
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: fleetmanager-client
    ports:
      - "4201:80"           
    depends_on:
      - server
    networks:
      - fleetnet

  # =============== BACKEND (.NET API) ===============
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fleetmanager-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=fleetdb;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - fleetnet

  # =============== DATABASE (PostgreSQL) ===============
  db:
    image: postgres:16
    container_name: fleetmanager-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fleetdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      - fleetnet

  # =============== PGADMIN (Database UI) ===============
  pgadmin:
    image: dpage/pgadmin4
    container_name: fleetmanager-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@volvo.com
      - PGADMIN_DEFAULT_PASSWORD=Fl3tM4n4G3r
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    depends_on:
      - db
    networks:
      - fleetnet

networks:
  fleetnet:

volumes:
  pgdata:
  pgadmin_data:
